// The deploy is only as good as its file list. Both failure modes it guards
// against are silent: an asset index.html asks for that never got staged (the
// app 404s on Pages but works locally), and a precached file missing from the
// tree (cache.addAll rejects, the worker never installs, the app is simply not
// offline). Neither shows up in any other test.
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { APP_DIRS, APP_FILES, DASHBOARD_FILES } from '../scripts/stage-pages.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const read = (path) => readFileSync(ROOT + path, 'utf8');

// Every relative URL index.html points at: stylesheets, the module entry, the
// manifest, the icon, and the import map's bare-specifier targets.
function referencedPaths(htmlFile) {
  const html = read(htmlFile);
  const attrs = [...html.matchAll(/(?:href|src)="(?!https?:|data:|#)([^"]+)"/g)].map(([, p]) => p);
  const importMap = html.match(/<script type="importmap">([\s\S]*?)<\/script>/);
  const mapped = importMap ? Object.values(JSON.parse(importMap[1]).imports) : [];
  return [...attrs, ...mapped].map((p) => p.replace(/^\.\//, ''));
}

const staged = (path) => APP_FILES.includes(path) || APP_DIRS.some((dir) => path.startsWith(`${dir}/`));

describe('pages staging', () => {
  it('stages every asset index.html references', () => {
    const refs = referencedPaths('index.html');
    expect(refs.length).toBeGreaterThan(5);
    expect(refs.filter((path) => !staged(path))).toEqual([]);
  });

  it('references only files that exist', () => {
    for (const path of referencedPaths('index.html')) {
      expect(existsSync(ROOT + path), path).toBe(true);
    }
  });

  it('stages every asset the dashboard references', () => {
    const listed = new Set(DASHBOARD_FILES.map(([, to]) => to));
    for (const path of referencedPaths('test-dashboard.html')) {
      // 'app/' is the app deploy next door, satisfied by the app staging below
      // rather than by a dashboard file. Everything else must be copied — and
      // note test-report.js is generated by the test run, so it may not exist
      // on disk yet; what matters is that the deploy is told to copy it.
      if (path === 'app/') continue;
      expect(listed.has(path), `${path} is referenced but not staged`).toBe(true);
    }
  });

  it('the app link the dashboard offers actually resolves to a page', () => {
    expect(referencedPaths('test-dashboard.html')).toContain('app/');
    expect(APP_FILES).toContain('index.html');
  });

  it('publishes nothing outside the app and the dashboard', () => {
    const publishable = [...APP_FILES, ...APP_DIRS, ...DASHBOARD_FILES.map(([from]) => from)];
    for (const path of publishable) expect(existsSync(ROOT + path), path).toBe(true);
    // test/, docs/, scripts/ and node_modules/ have no business on Pages.
    for (const secret of ['test', 'docs', 'scripts', 'node_modules', 'package.json']) {
      expect(publishable).not.toContain(secret);
    }
  });

  it('the workflow runs the staging script rather than its own copy of the list', () => {
    const workflow = read('.github/workflows/pages.yml');
    expect(workflow).toMatch(/node scripts\/stage-pages\.mjs/);
    expect(workflow).not.toMatch(/cp -r (icons|src|vendor)/);
  });

  it('the dashboard links to the deployed app', () => {
    expect(read('test-dashboard.html')).toMatch(/href="\.\/app\/"/);
  });
});
