// Metadata for the normative scenario tests T01–T17: literature anchor (AC +
// source) and evidence level, joined into test-report.js by
// scripts/build-report.mjs so the dashboard links each result to its science.
// `rules` feeds the R1–R8 coverage matrix.
export const SCENARIO_META = {
  T01: { desc: "Vier identische Einheiten (100 min · sRPE 6 = TL 600) im Abstand von je 7 Tagen. Akut-Fenster (7 d) enthält genau eine, das chronische Fenster (28 d) alle vier ⇒ chronischer Wochenschnitt 600, Ratio 600/600 = 1.00.", anchor: 'Lastmodell — Foster 2001 (sRPE-TL); ACWR Rolling Average (Gabbett 2016)', evidenceLevel: 'cohort', rules: ['R7'] },
  T02: { desc: "Reha-Rückkehr-Szenario: 4 Wochen reduzierte Basis, Bergtag (1150 hm) vor 30 h, harte Fingersession vor 20 h, volle geplante Woche. Erwartung: genau drei Interventionen, keine mehr, keine weniger.", anchor: 'Engine-Integration — Regelkatalog §4, Demo-Seed', evidenceLevel: '—', rules: ['R3', 'R4', 'R7'] },
  T03: { desc: "Harte Fingersession vor 20 h, heutiges Bouldern (fix) in ~3 h ⇒ Abstand ~23 h < 48 h. Fix schützt den Termin, also muss die Intervention reduce sein.", anchor: 'AC1/R3 — Pulley ≥48 h (Low; Climbing Doctor; Hooper’s Beta)', evidenceLevel: 'expert-consensus', rules: ['R3'] },
  T04: { desc: "Reine Beineinheit (alle Übungen belasten Beinregionen) 42 h nach 1150 hm Abstieg – innerhalb des DOMS-Fensters. Swap würde die Einheit aushöhlen (drop > keep), also greift der Fallback: move.", anchor: 'AC5/R4 — DOMS 24–72 h (Eston 1995; Reviews)', evidenceLevel: 'cohort', rules: ['R4'] },
  T05: { desc: "Niedrige chronische Basis (Reha) + volle geplante Woche ⇒ die Projektion ans Horizontende springt über 1.5. Bergtag und Boulderabende sind fix – nur der Lauf ist frei beweglich.", anchor: 'AC10/R7 — ACWR >1.5 (Gabbett 2016, BJSM 50(5):273–280)', evidenceLevel: 'cohort', rules: ['R7'] },
  T06: { desc: "Invariante über alle Vorschläge des Seeds: Auf fixe Einheiten sind nur inhaltliche Eingriffe (reduce, swap) erlaubt – nie move oder remove.", anchor: 'AC1/G4 — Fix-Schutz-Invariante (Spez §3.2)', evidenceLevel: '—', rules: ['R1', 'R3', 'R4', 'R5', 'R6', 'R7'] },
  T07: { desc: "Der move-Vorschlag legt die Beineinheit +2 Tage ⇒ ~90 h nach dem Abstieg, außerhalb des Fensters. Nach der Mutation darf R4 auf diese Einheit nicht erneut anschlagen.", anchor: 'Zustandsübergang — Annahme-Mutation (Spez §3.5)', evidenceLevel: '—', rules: ['R4'] },
  T08: { desc: "Ablehnen speichert den Key (Regel|Ziel) in rejected. Bei jeder Neubewertung wird dieser Key übersprungen – der Coach nervt nicht doppelt.", anchor: 'AC8/G3 — Ablehnungs-Persistenz (Spez §3.5)', evidenceLevel: '—', rules: ['R1', 'R3', 'R4', 'R5', 'R6', 'R7'] },
  T09: { desc: "Fingerschmerz NRS 7 und Finger-Erholung (R3) zielen beide auf das heutige Bouldern. Die Prioritätshierarchie (R1 = Tier 1) muss gewinnen; da die Einheit fix ist: reduce statt remove.", anchor: 'AC2/G5/R1 — Pain-Monitoring-Model (Silbernagel 2007, RCT)', evidenceLevel: 'rct', rules: ['R1', 'R3'] },
  T10: { desc: "3 von 4 Push-Übungen laden die Schulter ≥2 ⇒ Swap würde die Einheit aushöhlen (Guard). Fallback bei platt: move.", anchor: 'R5 — muskuläre Erholung 48–72 h (Trainingsphysiologie)', evidenceLevel: 'expert-consensus', rules: ['R5'] },
  T11: { desc: "Rotes Knie-Constraint sperrt alle Übungen mit Knie-Flexions-Tag. Die Legs-Einheit darf nur noch knie-freie Inhalte bauen.", anchor: 'AC6/R2 — Constraint-Substitution Knie (Beugetiefe)', evidenceLevel: 'expert-consensus', rules: ['R2'] },
  T12: { desc: "Generische Constraints (nicht nur Knie): rot sperrt die Region ⇒ jede Übung mit load[shoulder] ≥ 2 fliegt aus dem Pool.", anchor: 'R2 generisch — Region-Sperre über Load-Matrix', evidenceLevel: 'expert-consensus', rules: ['R2'] },
  T13: { desc: "Nach dem Loggen steckt die reale Last im Log. Der Plan-Eintrag (status=logged) muss aus Projektion und Regelprüfung verschwinden – sonst zählt die Session doppelt in die ACWR-Prognose.", anchor: 'Lastmodell-Integrität — keine Doppelzählung (Spez §3.5)', evidenceLevel: '—', rules: ['R3', 'R7'] },
  T14: { desc: "Gemischte Full-Body-Einheit im DOMS-Fenster: Statt die ganze Einheit zu verschieben, tauscht die Engine nur die Übungen, die Quads / hintere Kette / Waden ≥2 laden.", anchor: 'AC11/R4 — Übungsebene swap (Spez §3.4)', evidenceLevel: 'cohort', rules: ['R4'] },
  T15: { desc: "Wenn mehr als die Hälfte der Übungen betroffen wäre, ist Tauschen unehrlich – die Einheit wäre nicht mehr sie selbst. Dann bleibt die Engine bei move/reduce.", anchor: 'AC11/R4 — Aushöhl-Schutz (Spez §3.4)', evidenceLevel: 'cohort', rules: ['R4'] },
  T16: { desc: "Oberer Rücken müde vom Bouldern, geplante Upper-Session: Nur der schwere Pull-Anteil (Bent-Over Row) wird getauscht – Curl (Ellbogen/Unterarm) bleibt.", anchor: 'R5 — Übungsebene swap (Spez §3.4)', evidenceLevel: 'expert-consensus', rules: ['R5'] },
  T17: { desc: "Die Machbarkeits-Ampel pro Übung berechnet für den GEWÄHLTEN Tag: Back Squat ist 42 h nach dem Bergtag gesperrt (DOMS-Fenster + Beugetiefe), Bench ist frei. 4 Tage später ist das Bergtag-Fenster abgelaufen – nur der strukturelle Knie-Constraint bleibt.", anchor: 'AC13 — exerciseReadiness datumsabhängig (Spez §3.6)', evidenceLevel: '—', rules: ['R1', 'R2', 'R4', 'R5'] },
};
